version: '3'
networks:
  backend:
    driver: bridge

services:
  ruby:
    build: ./dock/ruby
    container_name: ruby-container
    tty: true
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - backend
